/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e235755;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CardTest {
    @Test void appHasAGreeting() {
        Card classUnderTest = new Card();
        //assertNotNull(classUnderTest.dealCards(), "app should have a greeting");
    }
}
